pipeline {
    agent any

    environment {
        AWS_REGION = 'us-east-2'
        REPOSITORY_URI = '504649076991.dkr.ecr.us-east-2.amazonaws.com/haider-jenkins'
    }

    stages {
        stage('Verify') {
            steps {
                sh '''
                    echo "Verifying contents of task13"
                    ls -la task13/
                    echo "Checking if AWS CLI is installed"
                    aws --version
                '''
            }
        }

        // stage('Build and Push') {
        //     steps {
        //         withCredentials([aws(accessKeyVariable: 'AWS_ACCESS_KEY_ID', credentialsId: 'haider-aws-creds', secretKeyVariable: 'AWS_SECRET_ACCESS_KEY')]) {
        //             sh '''
        //                 set -e
        //                 cd task13/

        //                 echo "Logging into Amazon ECR..."
        //                 aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $REPOSITORY_URI

        //                 echo "Determining Git commit hash for tagging..."
        //                 COMMIT_HASH=$(git rev-parse --short=7 HEAD)
        //                 echo "Using COMMIT_HASH: $COMMIT_HASH"

        //                 echo "Building Docker image..."
        //                 docker build -t haider-jenkins .

        //                 echo "Tagging Docker image with 'latest' and commit hash..."
        //                 docker tag haider-jenkins:latest $REPOSITORY_URI:latest
        //                 docker tag haider-jenkins:latest $REPOSITORY_URI:$COMMIT_HASH

        //                 echo "Pushing Docker images to ECR..."
        //                 docker push $REPOSITORY_URI:latest
        //                 docker push $REPOSITORY_URI:$COMMIT_HASH
        //             '''
        //         }
        //     }
        // }

        stage('Deploy') {
            steps {
                withCredentials([aws(accessKeyVariable: 'AWS_ACCESS_KEY_ID', credentialsId: 'haider-aws-creds', secretKeyVariable: 'AWS_SECRET_ACCESS_KEY')]) {
                    sh '''
                        aws ecs describe-task-definition --task-definition haider-td-jenkins > task-definition.json
                        cat task-definition.json
                        sed -i 's/\(:[^"]*\)latest/\1test/' task-definition.json
                        cat task-definition.json
                    '''
                }
            }
        }
    }
}