pipeline {
    agent any

    stages {
        stage('Verify') {
            steps {
                sh '''
                    echo "Verifying contents of task15..."
                    ls -la task15/
                '''
            }
        }

        stage('Build') {
            steps {
                sh '''
                    cd task15/app/

                    echo "Install Dependencies..."
                    npm install

                    echo "Creating artifact for deployment..."
                    tar -cvzf ../nodejs-app.tar.gz ./*
                '''
            }
        }

        stage('Deploy') {
            steps {
                sh '''
                    cd task15/
                    ls -la | grep nodejs-app.tar.gz
                '''

                sshagent(['nodejs-deployment-ec2']) {
                    sh '''
                        
                    '''
                }
            }
        }
    }
}