pipeline {
    agent any

    environment {
        EC2_PUBLIC_IP = '3.145.157.7'
    }

    stages {
        stage('Verify') {
            steps {
                sh '''
                    echo "Verifying contents of task15..."
                    ls -la task15/
                '''
            }
        }

        stage('Build') {
            steps {
                sh '''
                    cd task15/app/

                    echo "Install Dependencies..."
                    npm install

                    echo "Creating artifact for deployment..."
                    tar -cvzf ../nodejs-app.tar.gz ./*
                '''
            }
        }

        stage('Deploy') {
            steps {
                sh '''
                    echo "Verifying if artifact is in workspace..."
                    cd task15/
                    ls -la | grep nodejs-app.tar.gz
                '''

                sshagent(['nodejs-deployment-ec2']) {
                    sh '''
                        cd task15/

                        echo "Copying files to EC2..."
                        scp -o StrictHostKeyChecking=no ./deploy.sh ./nodejs-app.tar.gz ubuntu@$EC2_PUBLIC_IP:~

                        ssh -o StrictHostKeyChecking=no ubuntu@$EC2_PUBLIC_IP 'bash deploy.sh'
                    '''
                }
            }
        }
    }
}