version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
  pre_build:
    commands:
      - echo Changing directory to task12 and verifying contents...
      - cd task12/
      - ls -la
      - echo Verifying packages...
      - zip -v
      - node -v
      - npm -v
  build:
    commands:
    - cd app/
    - echo Installing dependencies...
    - npm install
    - echo Creating zip file for deployment...
    - zip -r eb-nodejs.zip ./*
    - ls -la
