version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
  pre_build:
    commands:
      - echo Changing directory to task12/app and verifying contents...
      - cd task12/app
      - ls -la
      - node -v
      - npm -v
  build:
    commands:
      - echo Build started on `date`
      - echo Installing dependencies...
      - npm install
      - echo Build completed on `date`
artifacts:
  base-directory: task12/app
  files:
    - '**/*'